### ISSUE TITLE
在RVIZ中显示机器人模型错误

### ISSUE THREAD

**Issue by mumuyanyan** [fishros/fishbot#3]
在RVIZ中显示机器人模型没有结果

<img width="906" alt="截屏2023-01-15 10 55 16" src="https://user-images.githubusercontent.com/13342178/212520586-97e4014d-0d91-4d1f-8e41-6215c11955ff.png">
<img width="1337" alt="截屏2023-01-15 10 57 03" src="https://user-images.githubusercontent.com/13342178/212520589-7bcb889e-32f6-4a93-a0a0-131b40ecc015.png">

**Comment by fishros** [comment]
请修改fixedframe 为base_link，参考教程：https://fishros.com/d2lros2/#/
